Feature/issue #15 login and role controllers
ASbeletsky/time-off-tracker-api pull request #18
Opened 2020-10-08 18:30 UTC by PedenkoIllia

Tested JWT and authorization. All work correct. 
I took JWT from: https://jasonwatmore.com/post/2019/10/16/aspnet-core-3-role-based-authorization-tutorial-with-example-api

2020-10-08 19:10 UTC, ASbeletsky requested changes

2020-10-08 19:10 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RoleController.cs
> +                    await _userManager.RemoveFromRolesAsync(user, userRole);
what for?

2020-10-08 19:10 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RoleController.cs
> +                    _logger.LogError(ex, "Cannot change user role: {UserId}", userId);
don't use try catch manually - you have it in exception handler. Better to throw Exception(like InvalidOperation or create a custom exception) with this message. Error handler will handle log it, then retrun BadRequest

2020-10-08 19:10 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Services/UserService.cs
> +                Expires = DateTime.UtcNow.AddDays(1),
move token lifetime to appsettings file

2020-10-08 19:15 UTC, PedenkoIllia commented on TimeOffTracker.WebApi/Controllers/RoleController.cs
> +                    await _userManager.RemoveFromRolesAsync(user, userRole);
I remove the old role after adding a new one

2020-10-10 09:27 UTC, ASbeletsky approved these changes

2020-10-10 13:06 UTC, merged