request controller added
ASbeletsky/time-off-tracker-api pull request #26
Opened 2020-10-13 13:11 UTC by TsypchenkoYuliia

2020-10-15 10:19 UTC, ASbeletsky requested changes

2020-10-15 10:19 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        public async Task<IReadOnlyCollection<TimeOffRequestApiModel>> Get()
we should have 2 urls:
GET /requests?userId=1 - gets all requests by user, only for manager, accounting and admin
GET /user/requests - get requests of current user - available for any role

both should have filter for startDate, endDate, state, type (look at mockaps of My Requests page)

2020-10-15 10:19 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        public async Task<TimeOffRequestApiModel> Get(int id)
we should have 2 urls:
GET /requests/{requestId} - gets requests by id, only for manager, accounting and admin
GET /user/requests/{requestId} - get requests by id of current user - available for any role

2020-10-15 10:19 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        public async Task Delete(int id)
we should have 2 urls:
DELETE /requests/{requestId} - delete request by id, only for admin
DELETE /user/requests/{requestId} - update request by id of current user  - sets request to rejected state - available for any role

2020-10-15 10:19 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +        {
here should be:

- timeOffTime validation - is it from enum or not
- start-end dates validation, look at spec, page # 7
- validation of reviewers - is accounting here, are reviewers in manager role?, for sick leave need on accounting etc  
- check if comments exists (for some vacation types it is required)
- check duration - should be full day for any type except sick leave
- set vacation state to New

2020-10-15 10:19 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        {
here should be model validation check for required fields

2020-10-15 10:19 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
>      public class TimeOffRequestService
create ITimeOffRequestService interface with appropriate methods, add to DI and inject in the controller

2020-10-15 10:19 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +        public TimeOffRequestService(TimeOffRequestRepository repository, IMapper mapper)
register TimeOffRequestRepository as  IRepository<TimeOffRequest, int> and inject IRepository<TimeOffRequest, int> here

2020-10-15 10:19 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +        {
please implement request update according to the spec, pages 10 - 11

2020-10-18 18:17 UTC, ASbeletsky requested changes

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        [Route("{userId:int}/{startDate}/{endDate}/{stateId:int}/{typeId:int}")]
As I said,this route should be /requests with optional query params:
int? userId,
DateTime? startDate,
DateTime? endDate,
int? stateId,
int? typeId

They should not be in the path!

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        [Route("{startDate}/{endDate}/{stateId:int}/{typeId:int}")]
As I said, this route should be /user/request with optional query params:
DateTime? startDate,
DateTime? endDate,
int? stateId,
int? typeId

They should not be in the path!

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        [Route("{userId:int}/{requestId:int}")]
As I said, this route should be /request/{requestId}
userId should not be in params

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        [Route("{requestId:int}")]
As I said, this route should be /user/requests/{requestId}

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +                if (model.TypeId > 0 && (model.TypeId < 8
Эта валидация должна быть в сервисе. Что я имел ввиду так это сформировать BadRequest с ошибками из ModelState если ModelState.IsValid == false

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        [HttpPut]
Роут должен быть /requests/{requestId}

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        public async Task Put(int userId, [FromForm] TimeOffRequestApiModel newModel)
Не FromForm, а FromBody, и убери userId

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        [Route("{userId:int}/{requestId:int}")]
/user/requests/{requestId}, убери userId

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/UsersController.cs
> +        [Authorize(Roles = "Admin")]
зачем?

2020-10-18 18:17 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/UsersController.cs
> +        [Authorize(Roles = "Admin")]
зачем?

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/Interfaces/ITimeOffRequestService.cs
> +    public interface ITimeOffRequestService<T> where T: class
Для чего параметр Т я так и не понял. Все что нужно это:
ITimeOffRequestService
{
        Task AddAsync(TimeOffRequestApiModel newRequest);
        Task<IReadOnlyCollection<TimeOffRequestApiModel>> GetAsync(int? userId, DateTime? start, DateTime? end, int? stateId, int? typeId);
        Task<TimeOffRequestApiModel> GetByIdAsync(int requestId);
        Task UpdateAsync(int requestId, TimeOffRequestApiModel updatedRequest);
        Task DeleteAsync(int requestId);
        Task RejectedAsync(int userId, int requestId);
    }

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                    return;
Создай кастомный ConfictException и выкинь его тут. Потом обработай его как 409 Conflict Response в контроллере

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            if(obj.TypeId == (int)TimeOffType.PaidLeave || obj.TypeId == (int)TimeOffType.AdministrativeUnpaidLeave || obj.TypeId == (int)TimeOffType.SickLeaveWithDocuments || obj.TypeId == (int)Time
Вынеси проверку в VadilateRequestComment метод и бросай в нем исключение или кастомное или ArgumentNull, которое потом обрабатывай в контроллере как 400 BadRequest

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                        if (!String.IsNullOrEmpty(obj.ProjectRole))
убери ProjectRole из модели, она не нужна

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            if (obj.TypeId == (int)TimeOffType.PaidLeave || obj.TypeId == (int)TimeOffType.AdministrativeUnpaidLeave || obj.TypeId == (int)TimeOffType.StudyLeave)
сделай 2 метода валидации
ValidateAccountingReviewer - где проверяешь наличие бухгалтерии (для всех типов отпуска)
ValidateManagerReviewers - где проверяешь наличие менеджеров (для нужных типов отпуска)

Если проверки не проходят - кидаешь исключение, аналогично, как я писал выше
В итоге тебе нужно будет просто вызвать последовательно эти 2 метода валидации и все

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                    if (obj.HasAccountingReviewPassed == true || obj.HasAccountingReviewPassed == false)
чтооо? для чего это?)

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                result.State = VacationRequestState.New;
зачем create и за ним update? просто перед созданием и прохождением всех проверок - поставь для RequestApiModel StateId = (int)VacationRequestState.New

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                && x.EndDate == end && x.State == (VacationRequestState)Enum.GetValues(typeof(VacationRequestState)).GetValue(stateId)
x.State == (VacationRequestState)Enum.GetValues(typeof(VacationRequestState)).GetValue(stateId)

по идее enum в базе хранятся как Int, поэтому это можно написать как (int) x.State == stateId, аналогично с Type

2020-10-18 18:17 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            var requestFromDb = await _repository.FindAsync(userId);
Где логика изменения только определенных полей согласно доке (стр 10 - 11) ?

2020-10-20 12:04 UTC, ASbeletsky requested changes

2020-10-20 12:04 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +                   if(ex is ConflictException)
выходит достаточно много условий, замени if-else на switch и вынеси это в 
https://github.com/ASbeletsky/time-off-tracker-api/blob/development/TimeOffTracker.WebApi/Filters/ExceptionFilter.cs

Там уже в зависимости от типа исключения - возвращай соответсвующий статус код и сообщение в body из exception.Message

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            foreach (var item in userRequests)
Для проверки на пересечение тебе не нужно вытаскивать все данные. Тебе достаточно 
bool hasIntersectionDates = _repository.FilterAsync(r => r.UserId == userId && (newRequest.EndDate < r.StartDate || newRequest.StartDate > r.EndDate)).Any() == false

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            obj.StateId = (int)VacationRequestState.New;
вынеси это из проверки в AddAsync, размести перед 
await _repository.CreateAsync(_mapper.Map<TimeOffRequest>(obj));

2020-10-20 12:04 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +                    await _service.AddAsync(model, int.Parse(this.User.Identity.Name));
сделай model.UserId = this.User.Identity.Name перед service.AddAsync и убери userId из параметров

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/Interfaces/ITimeOffRequestService.cs
> +        Task AddAsync(TimeOffRequestApiModel obj, int userId);
Task AddAsync(TimeOffRequestApiModel newRequest);

userId тебе не нужен отдельно, он есть в newRequest.UserId - ты его установишь в контроллере, если он не заполнен

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/Interfaces/ITimeOffRequestService.cs
> +        Task<IReadOnlyCollection<TimeOffRequestApiModel>> GetAllAsync(int userId, string start, string end, int stateId, int typeId);
Task<IReadOnlyCollection> GetAsync(int? userId, DateTime? start, DateTime? end, int? stateId, int? typeId);

я говорил что параметры должны быть nullable и даты не строки, а именно даты

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            catch (Exception ex)
убери пустой try-catch

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                    requestFromDb.Type = (TimeOffType)newModel.TypeId;
Используй маппер, вместо мапинга вручную

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                if(requestFromDb.EndDate.Date > DateTime.Now.Date)
Из доки: "Пользователь выбирает заявку в состоянии “Утверждена” (Approved), у которой
конечная дата (To) позже текущей даты" - ее тогда можно редактировать. А у тебя наоброт - нельзя.

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            }, duplicateModel.UserId);
используй мапер

2020-10-20 12:04 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                await Duplicate(_mapper.Map<TimeOffRequestApiModel>(requestFromDb));
У дубликата должна быть ссылка на стурую. Добать в TimeOffRequest поле ParentRequestId и установи его тут

2020-10-20 12:04 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        public async Task<IReadOnlyCollection<TimeOffRequestApiModel>> Get(int userId = 0, string startDate = null, string endDate = null, int stateId = 0, int typeId = 0)
пишу 3 раз - я уже устал, а ты?) параметры должны быть опциональны

2020-10-20 12:04 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        public async Task<IReadOnlyCollection<TimeOffRequestApiModel>> Get(string startDate = null, string endDate = null, int stateId = 0, int typeId = 0)
параметры должны быть опциональны

2020-10-20 12:04 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +                return HttpStatusCode.BadRequest;
Тебе не просто статус код нужно вернуть, а еще и ошибку их ModelState.Errors

2020-10-20 12:04 UTC, ASbeletsky commented on ApiModels/Models/TimeOffRequestApiModel.cs
>          public ICollection<TimeOffRequestReviewApiModel> Reviews { get; set; }
Мы договаривались еще добавть IEnumerable<int> ReviewersIds - тебе придут только id юзеров из которых тебе предстоит еще заполнить Reviews

2020-10-21 11:34 UTC, PedenkoIllia commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            foreach (var item in userRequests)
Возможно я ошибаюсь, но предложенный предикат достанет только те запросы, которые НЕ пересекаются с новым. Тут нужно примерно так:
`bool hasIntersectionDates = (await _repository.FilterAsync(r => r.UserId == userId && !(newRequest.EndDate < r.StartDate || newRequest.StartDate > r.EndDate))).Any();`

2020-10-22 11:40 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            foreach (var item in userRequests)
можно и так, только Any() == true

2020-10-22 11:51 UTC, ASbeletsky requested changes

2020-10-22 11:51 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                return (userRequests.Where((u => u.UserId == obj.UserId && (obj.StartDate >= u.StartDate && obj.StartDate <= u.EndDate) || (obj.EndDate <= u.EndDate && obj.StartDate >= u.StartDate)))
суть была в том что бы выполнить этот запрос в базе данных, а не в пямяти - вынеси этот Where в _repository.FilterAsync

2020-10-22 11:51 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +            if (requestFromDb.State == VacationRequestState.New)
напрашивается swith-case

2020-10-22 11:51 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Filters/ExceptionFilter.cs
> +            switch (context.Exception.GetType().Name)
используй pattern matching 
switch (context.Exception)
{
   case ConflictException conflictException: ...
}

2020-10-23 10:02 UTC, PedenkoIllia commented on TimeOffTracker.WebApi/appsettings.Development.json
> +    "defaultConnection": "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=_Tracker_;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWr
Зачем менять базу на локальную. Пусть в репозитории хранится строка подключения к удаленной БД. Если нужно что-то сделать через локальную БД, каждый может поменять строку подключения на свою.

2020-10-24 08:42 UTC, ASbeletsky approved these changes

2020-10-24 09:42 UTC, PedenkoIllia approved these changes

2020-10-24 16:04 UTC, merged