Feature/issue#27 email integration
ASbeletsky/time-off-tracker-api pull request #28
Opened 2020-10-19 17:09 UTC by PedenkoIllia

2020-10-20 19:31 UTC, ASbeletsky requested changes

2020-10-20 19:31 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/RequestUpdatedEmailHandelr.cs
> +                foreach (TimeOffRequestReview review in reviews)
это делается проще:
var approvedPeopleNames = reviews.Where(r => r.IsApproved).Select(r => r.Reviewer.FirstName + " " + r.Reviewer.LastName).ToList();

model.ApprovedFullNames = string.Join(", ", approvedPeopleNames);
address = reviews.Where(r => r.IsApproved).Select(r => r.Reviewer.Email).FirstOrDefautl();

2020-10-20 19:31 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/RequestUpdatedEmailHandelr.cs
> +            if (request.HasAccountingReviewPassed)
по не используй HasAccountingReviewPassed флаг, может мы его уберем, не уверен что он нужен

2020-10-20 19:31 UTC, ASbeletsky commented on BusinessLogic/Notifications/RequestUpdatedNotification.cs
> +    class RequestUpdatedNotification : RequestChangedNotification
ты уже или раздели на RequestCreatedNotification и RequestUpdatedNotification или используй пока везде RequestChangedNotification

2020-10-20 19:31 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/RequestUpdatedEmailHandelr.cs
> +                address = users.FirstOrDefault().Email;
этот класс ничего не должен знать о порядке апруверов - бери почту из Reviewer.Email как и для менеджеров

2020-10-20 19:31 UTC, ASbeletsky commented on BusinessLogic/Resources/Email.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
переименуй на Email.ru.resx

2020-10-20 19:31 UTC, ASbeletsky commented on TimeOffTracker.WebApi/EmailTemplates/EmailAboutRequestUpdateBody_ru
> +﻿  <body>
чет не нрав мне хранить разметку в файле, давай прикрутим таки разор.
Создай отдельный Razor class library и в нем храни раметку. Вот пример
https://scottsauber.com/2018/07/07/walkthrough-creating-an-html-email-template-with-razor-and-razor-class-libraries-and-rendering-it-from-a-net-standard-class-library/

Используй файл ресурсов и локализацию вьюх как описано тут
https://metanit.com/sharp/aspnet5/28.5.php

2020-10-22 09:45 UTC, PedenkoIllia commented on BusinessLogic/Notifications/RequestUpdatedNotification.cs
> +    class RequestUpdatedNotification : RequestChangedNotification
Я думал сделать общий класс нотификации по заявке, а от него наследовать RequestUpdate, RequestCreate, RequestReject. Можно и просто отдельные создать

2020-10-25 08:50 UTC, ASbeletsky requested changes

2020-10-25 08:50 UTC, ASbeletsky commented on RazorLibrary/RazorLibrary.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Razor">
переименуй проект на EmailTemplateRender

2020-10-25 10:57 UTC, merged