reviews api added
ASbeletsky/time-off-tracker-api pull request #31
Opened 2020-10-25 13:05 UTC by TsypchenkoYuliia

2020-10-26 10:01 UTC, ASbeletsky requested changes
Тебе еще нужно обновить TimeOffRequestService что бы доделать то ты не доделала так как не было еще логики по RequestReview 
И зарезолви конфикты

2020-10-26 10:01 UTC, ASbeletsky commented on BusinessLogic/Services/Interfaces/ITimeOffRequestReviewService.cs
> +        Task<IReadOnlyCollection<TimeOffRequestReviewApiModel>> GetAllAsync(int userId, int? stateId = null, DateTime? startDate = null, DateTime? endDate = null, string name = null, int? typeId = nu
userId должно быть nullable
name - не нужен, достаточно только userId, он будет получен на фронте через /users?name=abc

2020-10-26 10:01 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/ReviewsController.cs
> +        [HttpPut("/reviews")]
для кого этот эндпоинт?

2020-10-26 10:01 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/ReviewsController.cs
> +        [Authorize(Roles = "Manager, Accountant, Employee")]
Employee не может сам себе апрувить отпуск)

2020-10-26 10:01 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/ReviewsController.cs
> +        [HttpPut("/reviews/{id}")]
как я вижу этот эндпоинт работает только с заявками текущего менеджера/админа -  поэтому лучше сделать роут PUT /reviews/user/{reviewId}

2020-10-26 10:01 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +
нужно добавить проверку что этот менеджер (userId) является ревьювером по этой заявке - если нет, кидать ошибку

2020-10-26 10:01 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +                if (reviewfromDb.Request.Reviews.FirstOrDefault(x => x.ReviewerId == userId) == null)
можно не тянуть всех ревьюверов, а делать _requestsRepository.FindAsync(r => r.Id == reviewfromDb.RequestId && r.ReviewersIds.Contains(userId)).Any() == false

2020-10-26 10:01 UTC, ASbeletsky commented on DataAccess/Repository/TimeOffRequestReviewRepository.cs
> +                    .ThenInclude(u => u.User)
лучше не делать такую сильную вложенность, убери джоины на Юзеров:
.ThenInclude(u => u.User) 
.Include(r => r.Reviewer)

2020-10-26 10:01 UTC, ASbeletsky commented on DataAccess/Repository/TimeOffRequestReviewRepository.cs
> +        }
убери вложеность на юзеров, как я писал выше

2020-10-26 10:01 UTC, ASbeletsky commented on Domain/EF_Models/TimeOffRequestReview.cs
> +
Добавть еще дату обновления ревью DateTime UpdatedAt {get; set;}

2020-10-26 10:01 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +                    reviewfromDb.Request.HasAccountingReviewPassed = true;
давай удалим Request.HasAccountingReviewPassed вообще, я не вижу в нем смысла

2020-10-26 10:01 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +                if (reviewfromDb.Request.Reviews.All(x => x.IsApproved != null))
это нужно следать в отдельном OnRequestReviewUpdateHandler-е с помощью MediatR - нужно добавить нотификацию о том что было обновленно ревью, и в нем обновить состояние заявки если все ревью IsApproved == true.
Можешь узнать у @PedenkoIllia он уже делал нечто подобное для формирования писем

2020-10-26 10:01 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +        private bool isReapproval(TimeOffRequestReview review, int reviewerId)
такую же проверку нужно делать и при повторном отклонении.

2020-10-27 10:11 UTC, TsypchenkoYuliia commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +        private bool isReapproval(TimeOffRequestReview review, int reviewerId)
private bool isReapproval(TimeOffRequestReview review, int reviewerId) метод проверяет обработал или нет менеджер этот реквест. Если ревью этого менеджера уже есть в списке ревью этого реквеста и поле IsApproved != null (по дефолту оно null, true или false становиться в процессе ревью) то будет исключение
if (isReapproval(reviewfromDb, userId))
                    throw new ConflictException("The request has already been approved!");

2020-10-27 10:11 UTC, TsypchenkoYuliia commented on BusinessLogic/Services/Interfaces/ITimeOffRequestReviewService.cs
> +        Task<IReadOnlyCollection<TimeOffRequestReviewApiModel>> GetAllAsync(int userId, int? stateId = null, DateTime? startDate = null, DateTime? endDate = null, string name = null, int? typeId = nu
Я неверно его назвала, это не userId, это reviewerId, по которому я запрашиваю все ревью менеджера/бухгалтера, исправила на reviewerId

2020-10-29 12:22 UTC, ASbeletsky requested changes

2020-10-29 12:22 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/OnRequestReviewUpdateHandler.cs
> +            if (requestfromDb.Reviews.All(x => x.IsApproved != null))
как раз если All(x => x.IsApproved != null) то статус InProgress, а когда All(x => x.IsApproved) тогда статус Approved

2020-10-29 12:22 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/ReviewsController.cs
> +        [HttpGet("/reviews")]
учитывая что это ревью только текущего пользователя лучше роут назвать /user/reviews

и добавть эндпоинт /reviews для роли админ, куда можно передать кроме остальных параметров еще int? reviewerId

2020-10-29 12:22 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/ReviewsController.cs
> +        [HttpPut("/reviews/user/{id}")]
раз выше эндпоинт /user/reviews, то лучше сделать этот /user/reviews/{id}

2020-10-29 12:22 UTC, ASbeletsky commented on BusinessLogic/Services/Interfaces/ITimeOffRequestReviewService.cs
> +        Task<IReadOnlyCollection<TimeOffRequestReviewApiModel>> GetAllAsync(int reviewerId, int? stateId = null, DateTime? startDate = null, DateTime? endDate = null, string name = null, int? typeId
сделай reviewerId nullable и добавть еще int? requestId параметр, что бы можно было потом получить все ревью по заявке. Добавь этот параметр и в контроллер тоже

2020-10-29 12:22 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +        private bool isReapproval(TimeOffRequestReview review, int reviewerId)
вот именно. Как раз если я делаю reject по завяве в которой IsApproved равно false то я увижу "The request has already been approved!", а не "The request has already been rejected!". Ты выше делаешь проверку на rejected. Что бы не делать 2 проверки на rejected и approve нужно переменовать этот метод на IsReviewPassed и если да, то кидать ошибку The request has already been <approved/rejected>!

2020-10-29 12:22 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +            if((await _requestRepository.FilterWithIncludeAsync(r => r.Id == reviewfromDb.RequestId
я говорил тебе не делать вложености на Reviewer. Пишу еще раз:

bool reviwerIsMissed = _requestsRepository.Filter(r => r.Id == reviewfromDb.RequestId && r.ReviewersIds.Contains(userId)).Any() == false

или можно вытащить Request из _requestsRepository по айди и проверить в памяти

if(reviwerIsMissed) throw new ConflictException("The request is not actual!");

2020-10-29 12:22 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestReviewService.cs
> +            var notification = new ReviewUpdateHandler { Request = reviewfromDb.Request };
ты не должна получать Request из reviewfromDb. Если тебе нужен Request тебе нужно его подтянуть из _requestRepository

2020-10-30 16:42 UTC, PedenkoIllia requested changes

2020-10-30 16:42 UTC, PedenkoIllia commented on BusinessLogic/NotificationHandlers/OnRequestReviewUpdateHandler.cs
> +                await _requestRepository.UpdateAsync(requestfromDb);
После утверждения заявки, нужно кидать RequestApprovedNotification (по примеру RequestUpdatedNotification).

2020-10-31 14:13 UTC, PedenkoIllia requested changes

2020-10-31 14:13 UTC, PedenkoIllia commented on BusinessLogic/NotificationHandlers/OnRequestReviewUpdateHandler.cs
> +                requestfromDb.State = VacationRequestState.Rejected;
Если в этом обработчике возможна установка состояния Rejected, то нужно предусмотреть кидание соответствующей нотификации (RequestRejectedNotification). 
Можно объявить `INotification mailNotification` и присваивать в неё нужный тип уведомления в каждом if (после `requestfromDb.State =`). Отсылать после `await _requestRepository.UpdateAsync(requestfromDb);`

2020-10-31 14:13 UTC, PedenkoIllia commented on BusinessLogic/NotificationHandlers/OnRequestReviewUpdateHandler.cs
> +            var notification_approved = new RequestApprovedNotification { Request = await _requestRepository.FindAsync(notification.Request.Id) };
Зачем лишний раз искать то, что уже есть? requestfromDb после UpdateAsync является той самой заявкой. Либо можно передать notification.Request. Разницы быть не должно.

2020-10-31 17:00 UTC, PedenkoIllia approved these changes

2020-10-31 18:31 UTC, PedenkoIllia commented on DataAccess/Repository/TimeOffRequestRepository.cs
> +        public async override Task<IReadOnlyCollection<TimeOffRequest>> FilterAsync(Expression<Func<TimeOffRequest, bool>> predicate)
Аналогично вызову FilterWithIncludeAsync(<predicate>, r => r.Reviews)

2020-11-01 10:33 UTC, ASbeletsky approved these changes

2020-11-01 10:34 UTC, merged