Create request approved email
ASbeletsky/time-off-tracker-api pull request #33
Opened 2020-10-26 13:11 UTC by PedenkoIllia

Поскольку начальное заполнение модели с данными идентично для всех писем, предлагаю после добавления всех трех типов писем вынести эту часть в отдельный класс и вызывать/наследовать его в остальных обработчиках. Иначе будет повторение идентичного кода в трех обработчиках

2020-10-27 09:21 UTC, PedenkoIllia commented
![image](https://user-images.githubusercontent.com/70018123/97281598-623eeb00-1846-11eb-8b9f-92c374dc0497.png)
––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
![image](https://user-images.githubusercontent.com/70018123/97281630-6bc85300-1846-11eb-893d-bbff55eafd75.png)

2020-10-27 09:51 UTC, PedenkoIllia commented
Можно объединить все в один класс и просто проверять состояние заявки. По состоянию заявки делать письма про update, approved или reject. Тогда обработчик будет жирным, но не придется дублировать код.

2020-10-30 16:00 UTC, ASbeletsky requested changes

2020-10-30 16:00 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/RequestApprovedEmailHander.cs
> +    class RequestApprovedEmailHander : INotificationHandler<RequestApprovedNotification>
Напиши в ревью @PedenkoIllia (ее пр https://github.com/ASbeletsky/time-off-tracker-api/pull/31)
что нужно добавить прокидываение RequestApprovedNotification в файл

https://github.com/ASbeletsky/time-off-tracker-api/blob/issue%2330_adding_review_api/BusinessLogic/NotificationHandlers/OnRequestReviewUpdateHandler.cs

И проследи выполнение путем апрува или реджекта ПРа

2020-10-30 16:00 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/RequestApprovedEmailHander.cs
> +            IEnumerable<TimeOffRequestReview> reviews = await _reviewRepository.FilterWithIncludeAsync(rev => rev.RequestId == request.Id, rev => rev.Reviewer);
Доставай юзеров отдельно или через ропозиторий или через UserManager по ReviewerIds, не нужно их инклудить

2020-10-30 16:24 UTC, PedenkoIllia commented on BusinessLogic/NotificationHandlers/RequestApprovedEmailHander.cs
> +            IEnumerable<TimeOffRequestReview> reviews = await _reviewRepository.FilterWithIncludeAsync(rev => rev.RequestId == request.Id, rev => rev.Reviewer);
Incllude это неправильный подход в случае Generic Repository, или это неправильно в данном случае?

2020-10-30 16:55 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/RequestApprovedEmailHander.cs
> +            IEnumerable<TimeOffRequestReview> reviews = await _reviewRepository.FilterWithIncludeAsync(rev => rev.RequestId == request.Id, rev => rev.Reviewer);
В данном случае, так как юзеры часто отделаются от останых сущностей.

2020-11-02 10:33 UTC, ASbeletsky approved these changes

2020-11-02 10:53 UTC, merged