Added first variant of reject by owner logic
ASbeletsky/time-off-tracker-api pull request #39
Opened 2020-11-02 14:30 UTC by PedenkoIllia

2020-11-07 10:56 UTC, ASbeletsky requested changes

2020-11-07 10:56 UTC, ASbeletsky commented on ApiModels/Models/TimeOffRequestApiModel.cs
> +        public int RejectTypeId { get; set; }
я думаю можно обойтись без этого. Просто если заявка отклонена и у нее нет rejected ревью, значит она отклонена самим создателем. Поэтому давай удалим RejectTypeId

2020-11-07 10:56 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +        public async Task ModifyAfterApprovedAsync(int userId, int requestId, TimeOffRequestApiModel modifyRequest)
Не понял зачем нам этот метод. Для изменения подтвержденной заявки или заявке в процессе  тебе нужно вносить изменения в метод UpdateAsync

2020-11-07 11:08 UTC, PedenkoIllia commented on ApiModels/Models/TimeOffRequestApiModel.cs
> +        public int RejectTypeId { get; set; }
А как обрабатывать Modify by the owner? Или мы будем с ним работать аналогично Reject by the owner?

2020-11-07 11:17 UTC, PedenkoIllia commented on BusinessLogic/Services/TimeOffRequestService.cs
> +        public async Task ModifyAfterApprovedAsync(int userId, int requestId, TimeOffRequestApiModel modifyRequest)
Не заметил, что там уже есть заготовка под это. Переделаю

2020-11-07 18:35 UTC, PedenkoIllia commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        public async Task ModifyAfterApproved(int requestId, [FromBody] TimeOffRequestApiModel newModel)
Теперь код этого эндпоинта полностью совпал с обычным эндпоинтом изменения заявки. Можно убрать этот эндпоинт и при модификации автором ссылаться на уже существующий эндпоинт

2020-11-08 12:01 UTC, ASbeletsky requested changes

2020-11-08 12:01 UTC, ASbeletsky commented on TimeOffTracker.WebApi/Controllers/RequestController.cs
> +        public async Task ModifyAfterApproved(int requestId, [FromBody] TimeOffRequestApiModel newModel)
можно убрать, да

2020-11-08 12:01 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                        safeModel.ParentRequestId = requestFromDb.Id;                       //prevent date intersection
Ты читал код который тут был? Тут был метод Duplicate для дублирования заявки - верни его и помести логику копирования заявки в него

2020-11-08 12:01 UTC, ASbeletsky commented on Domain/Enums/TimeOffRejectType.cs
> +    public enum TimeOffRejectType : int
удали это

2020-11-08 12:01 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/RequestRejectEmailHandelr.cs
> +            if (request.RejectType == TimeOffRejectType.ModifyByAuthor)
не понял зачем это, убери

2020-11-08 12:01 UTC, ASbeletsky commented on Domain/EF_Models/TimeOffRequest.cs
> +        public TimeOffRejectType RejectType { get; set; }
вместо этого добавь int? ModifiedByUserId

2020-11-08 12:01 UTC, ASbeletsky commented on BusinessLogic/NotificationHandlers/RequestRejectEmailHandelr.cs
> +            bool isDeclineByTheOwner = request.RejectType == TimeOffRejectType.RejectByAuthor;
bool isDeclineByTheOwner = request.State == Rejected && request.ModifiedByUserId == author.Id

2020-11-08 12:01 UTC, ASbeletsky commented on BusinessLogic/Services/TimeOffRequestService.cs
>              {
добавь логику обновления и для стейта InProgress в этот пр

2020-11-08 12:13 UTC, PedenkoIllia commented on Domain/EF_Models/TimeOffRequest.cs
> +        public TimeOffRejectType RejectType { get; set; }
Понял. В ApiModel нужно выносить это свойство?

2020-11-08 12:14 UTC, PedenkoIllia commented on BusinessLogic/Services/TimeOffRequestService.cs
> +                        safeModel.ParentRequestId = requestFromDb.Id;                       //prevent date intersection
Я думал, что это метод заготовка для Дублирования заявки из ТЗ. Но по факту там имелось ввиду создание новой заявки по шаблону. Ошибся из-за названия. Вынесу код "модификации после утверждения" в метод Duplicate

2020-11-09 19:55 UTC, ASbeletsky commented on Domain/EF_Models/TimeOffRequest.cs
> +        public TimeOffRejectType RejectType { get; set; }
да

2020-11-10 20:19 UTC, ASbeletsky approved these changes

2020-11-10 20:27 UTC, merged